### ISSUE TITLE
Samsung Galaxy Tab S (SM-T700) system ui crash

### ISSUE THREAD

**Issue by sdex** [vfarafonov/DroidShoter#3]
Запустил на данном девайсе, после нескольких скриншотов упал System UI на девайсе, следом за ним TouchWiz. Оболочка больше не грузилась даже после ребута. 
Hard reset.

**Comment by vfarafonov** [comment]
Добрый день.
Печально слышать. Надеюсь, важные данные не потерялись.
Можете сообщить версию Android? Прошивка, как я понимаю, официальная?
Спасибо за Ваш репорт.

**Comment by sdex** [comment]
Прошивка официальная, версия 5.0.2. 
Скорее всего, Вы, как разработчик, здесь сделать ничего не сможете, девайсы от самсунга славятся своими багами и болью для разработчиков. 
Было бы хорошо в readme указать на возможные последствия. 
Девайс исключительно для девелопмента, так что все в порядке.

**Comment by vfarafonov** [comment]
Да, я как разработчик могу максимум выдать диалог "О нет, опять Самсунг" при его подключении :)
Readme обновлю скоро, статью на хабре обновил сразу, как увидел issue.
Еще раз спасибо.

**Comment by vitas** [comment]
самсунг это проклятье аднроид разработчиков. ни одна програ не обходится без воркераундов для их девайсов.
